import { z } from "zod";

export const createPacienteSchema = z.object({
  nome: z.string().min(2, "Nome deve ter pelo menos 2 caracteres"),
  cpf: z.string().min(11, "CPF inválido"),
  rg: z.string().optional(),
  dataNascimento: z.string().transform((s) => new Date(s)),
  sexo: z.string().min(1, "Sexo é obrigatório"),
  estadoCivil: z.enum(["SOLTEIRO", "CASADO", "DIVORCIADO", "VIUVO", "UNIAO_ESTAVEL"]),
  profissao: z.string().optional(),
  telefone: z.string().optional(),
  email: z.string().email().optional().or(z.literal("")),
  endereco: z.string().optional(),
  bairro: z.string().optional(),
  cidade: z.string().optional(),
  uf: z.string().optional(),
  cep: z.string().optional(),
  substanciaPrincipal: z.string().optional(),
  tempoUso: z.string().optional(),
  internacoesPrevias: z.number().int().min(0).default(0),
  comorbidades: z.string().optional(),
  alergias: z.string().optional(),
  dataAdmissao: z.string().transform((s) => new Date(s)),
  dataAltaPrevista: z.string().optional().transform((s) => (s ? new Date(s) : undefined)),
  diasTratamento: z.number().int().min(1, "Dias de tratamento deve ser pelo menos 1"),
  quartoId: z.string().uuid().optional(),
  matriculaValor: z.number().optional(),
  mensalidadeValor: z.number().optional(),
  diaVencimento: z.number().int().optional(),
  responsavel: z
    .object({
      nome: z.string().min(2),
      cpf: z.string().min(11),
      dataNascimento: z.string().optional().transform((s) => (s ? new Date(s) : undefined)),
      profissao: z.string().optional(),
      estadoCivil: z.enum(["SOLTEIRO", "CASADO", "DIVORCIADO", "VIUVO", "UNIAO_ESTAVEL"]).optional(),
      parentesco: z.string().min(1),
      telefone: z.string().min(8),
      email: z.string().email().optional().or(z.literal("")),
      endereco: z.string().optional(),
      isFinanceiro: z.boolean().default(true),
    })
    .optional(),
});

export const updatePacienteSchema = z.object({
  nome: z.string().min(2).optional(),
  cpf: z.string().min(11).optional(),
  rg: z.string().optional(),
  dataNascimento: z.string().transform((s) => new Date(s)).optional(),
  sexo: z.string().optional(),
  estadoCivil: z.enum(["SOLTEIRO", "CASADO", "DIVORCIADO", "VIUVO", "UNIAO_ESTAVEL"]).optional(),
  profissao: z.string().optional(),
  telefone: z.string().optional(),
  email: z.string().email().optional().or(z.literal("")),
  status: z.enum(["ATIVO", "ALTA", "EVADIDO", "TRANSFERIDO", "OBITO"]).optional(),
  endereco: z.string().optional(),
  bairro: z.string().optional(),
  cidade: z.string().optional(),
  uf: z.string().optional(),
  cep: z.string().optional(),
  substanciaPrincipal: z.string().optional(),
  tempoUso: z.string().optional(),
  internacoesPrevias: z.number().int().min(0).optional(),
  comorbidades: z.string().optional(),
  alergias: z.string().optional(),
  dataAdmissao: z.string().transform((s) => new Date(s)).optional(),
  dataAltaPrevista: z.string().optional().transform((s) => (s ? new Date(s) : undefined)),
  dataAlta: z.string().optional().transform((s) => (s ? new Date(s) : undefined)),
  diasTratamento: z.number().int().min(1).optional(),
  quartoId: z.string().uuid().optional().nullable(),
  matriculaValor: z.number().optional(),
  mensalidadeValor: z.number().optional(),
  diaVencimento: z.number().int().optional(),
});

export type CreatePacienteInput = z.infer<typeof createPacienteSchema>;
export type UpdatePacienteInput = z.infer<typeof updatePacienteSchema>;
